// AUTO-GENERATED by scripts/bootstrap-workspace.ts — do not edit manually.
// Run `pnpm tsx scripts/bootstrap-workspace.ts` to re-populate.

import type { SquadId } from "../types/core";

export interface NotionIds {
  dbs: {
    mirrorGithub: string;
    mirrorJira: string;
    mirrorSlack: string;
    mirrorFigma: string;
    squads: string;
    prds: string;
    productRoadmap: string;
    squadWeeklySummary: string;
    masterEpdWeekly: string;
    agentRunLog: string;
    deliveryPipeline: string;
    hitlReviewSessions: string;
  };
  pages: {
    squadAtlas: string;
    squadLumen: string;
    squadForge: string;
  };
}

export const NOTION_IDS: NotionIds = {
  dbs: {
    mirrorGithub:       "36efc8f4-554c-81d7-85ac-d35f95eb69e4",  // "GitHub | Mirror"
    mirrorJira:         "36efc8f4-554c-819f-8f3e-d03323cbbf71",  // "Jira | Mirror"
    mirrorSlack:        "36efc8f4-554c-81bd-af9b-c3564c1c4522",  // "Slack | Mirror"
    mirrorFigma:        "36efc8f4-554c-81e0-b50e-d63ca48e5f3c",  // "Figma | Mirror"
    squads:             "36efc8f4-554c-81f7-b7c9-ccf08de3d6a1",
    prds:               "36efc8f4-554c-81fc-87de-c7eb7e467521",
    productRoadmap:     "36efc8f4-554c-818c-99ac-c63a7bdfb9fa",
    squadWeeklySummary: "36efc8f4-554c-819e-b339-ec0bb2c97a76",
    masterEpdWeekly:    "36efc8f4-554c-8158-808b-d084ce4c4a16",
    agentRunLog:        "36efc8f4-554c-814e-8c51-ea51792f5344",
    deliveryPipeline:   "36efc8f4-554c-813a-8e52-d26b831109fe",
    hitlReviewSessions: "370fc8f4-554c-8113-a6dd-f893a84555ff",
  },
  pages: {
    squadAtlas: "36efc8f4-554c-81e7-a83b-c976963a5fab",  // Atlas row in Squads DB
    squadLumen: "36efc8f4-554c-81b6-8583-dd3634f0e7ad",  // Lumen row in Squads DB
    squadForge: "36efc8f4-554c-8102-b02e-d9def2d4a4da",  // Forge row in Squads DB
  },
};

const SQUAD_PAGE_IDS: Record<SquadId, string> = {
  atlas: NOTION_IDS.pages.squadAtlas,
  lumen: NOTION_IDS.pages.squadLumen,
  forge: NOTION_IDS.pages.squadForge,
};

export function getSquadPageId(squadId: SquadId): string {
  return SQUAD_PAGE_IDS[squadId];
}
