// AUTO-GENERATED by scripts/bootstrap-workspace.ts — do not edit manually.
// Run `pnpm tsx scripts/bootstrap-workspace.ts` to re-populate.
// Extra dbs fields added by external patches are preserved via read-merge.
//
// EPD databases use the 36efc8f4… set: the populated Round 1 workspace
// (GitHub Mirror, summaries, Agent Run Log, etc.). GTM databases use the 377…
// set created by scripts/patch-schema-round2.ts under the "Revenue" sub-page.
//
// ⚠️  Bootstrap title-scan picks up duplicate 377fc8f4-… stubs created by the
//     PRD-13 incident instead of the live 36efc8f4-… data set. Do NOT re-run
//     bootstrap against the live workspace — use `ntn` CLI for schema changes.
//
// hitlReviewSessions added by PRD-06 patch.

import type { SquadId } from "../types/core";

export interface NotionIds {
  dbs: {
    mirrorGithub: string;
    mirrorJira: string;
    mirrorSlack: string;
    mirrorFigma: string;
    squads: string;
    prds: string;
    productRoadmap: string;
    squadWeeklySummary: string;
    masterEpdWeekly: string;
    agentRunLog: string;
    deliveryPipeline: string;
    hitlReviewSessions: string;
    // Round 2 GTM databases — set by patch-schema-round2.ts
    gtmMeetingNotes: string;
    opportunities: string;
    gtmDailyDigest: string;
    battleCards: string;
    // Added 2026-06-07: replaces the original "GTM Weekly Briefs" page-hierarchy
    // design (Revenue > GTM Weekly Briefs > GTM Weekly — {weekOf}) with a proper
    // database — one row per week, mirroring Master EPD Weekly. See PRD-13 Addendum.
    gtmWeeklyBriefs: string;
  };
  pages: {
    squadAtlas: string;
    squadLumen: string;
    squadForge: string;
    revenue: string;
  };
}

export const NOTION_IDS: NotionIds = {
  dbs: {
    mirrorGithub:       "36efc8f4-554c-81d7-85ac-d35f95eb69e4",  // "GitHub | Mirror"
    mirrorJira:         "36efc8f4-554c-819f-8f3e-d03323cbbf71",  // "Jira | Mirror"
    mirrorSlack:        "36efc8f4-554c-81bd-af9b-c3564c1c4522",  // "Slack | Mirror"
    mirrorFigma:        "36efc8f4-554c-81e0-b50e-d63ca48e5f3c",  // "Figma | Mirror"
    squads:             "36efc8f4-554c-81f7-b7c9-ccf08de3d6a1",
    prds:               "36efc8f4-554c-81fc-87de-c7eb7e467521",
    productRoadmap:     "36efc8f4-554c-818c-99ac-c63a7bdfb9fa",
    squadWeeklySummary: "36efc8f4-554c-819e-b339-ec0bb2c97a76",
    masterEpdWeekly:    "36efc8f4-554c-8158-808b-d084ce4c4a16",
    agentRunLog:        "36efc8f4-554c-814e-8c51-ea51792f5344",
    deliveryPipeline:   "36efc8f4-554c-813a-8e52-d26b831109fe",
    hitlReviewSessions: "370fc8f4-554c-8113-a6dd-f893a84555ff",
    // Round 2 GTM databases (377… set, under the "Revenue" sub-page)
    gtmMeetingNotes:    "377fc8f4-554c-81b1-b388-d5aa65781f01",  // "GTM | Meeting Notes"
    opportunities:      "377fc8f4-554c-81b8-ba74-cc69fc66d19d",  // "GTM | Opportunities"
    gtmDailyDigest:     "377fc8f4-554c-8120-9027-f33bf647c36b",  // "GTM | Daily Digest"
    battleCards:        "377fc8f4-554c-8113-aa58-f4c21e1fa2c4",  // "GTM | Battle Cards"
    // Created live by Dan via the Notion UI on 2026-06-08 (after automated-creation
    // attempts were correctly blocked by the safety classifier — see PRD-13 Addendum
    // for the fork-incident history). Verified via `ntn api v1/databases/{id}`:
    // archived=false, properties match spec exactly (Title/title, Week Of/date,
    // Status/select draft+published, Deals Flagged/number, Flagged Deals/relation
    // → dbs.opportunities). NOT the "379fc8f4-554c-819d-…" stub from the fork —
    // that ID is a different, now-archived duplicate; this one is live and correct.
    gtmWeeklyBriefs:    "379fc8f4-554c-803c-acbb-dccd29e576bf",  // "GTM | Weekly Briefs"
  },
  pages: {
    squadAtlas: "36efc8f4-554c-81e7-a83b-c976963a5fab",  // Atlas row in Squads DB
    squadLumen: "36efc8f4-554c-81b6-8583-dd3634f0e7ad",  // Lumen row in Squads DB
    squadForge: "36efc8f4-554c-8102-b02e-d9def2d4a4da",  // Forge row in Squads DB
    // ⚠️  STALE — ARCHIVED 2026-06-0x, do not use as a live parent. Verified via
    //     `ntn api v1/search` (2026-06-08): archived=true, zero live children.
    //     The live GTM databases + "GTM Weekly Briefs" page do NOT live under this
    //     page — they're inline-embedded in a column layout directly on the base
    //     page (under a "Summaries" callout: column_list 378fc8f4-…809e). There is
    //     no single "Revenue" container in the live workspace; each GTM DB ID is
    //     stored directly above and is the source of truth, not this field.
    //     ⚠️  `REVENUE_PAGE_ID` is ALSO hardcoded (same archived ID) in
    //     workers/summarizer-master/src/index.ts and scripts/generate-master.ts —
    //     their "find or create GTM Weekly Briefs page" search filters on
    //     `parent.page_id === REVENUE_PAGE_ID`, but the live page's parent is a
    //     `block_id` (a column), so the match always fails and falls through to
    //     `pages.create({ parent: { page_id: REVENUE_PAGE_ID }})` — which targets
    //     an archived page. Next `pnpm generate-master` run will likely error or
    //     create orphans. FIX: this whole traversal is obsoleted by the PRD-13
    //     Addendum + PRD-17 spec update converting GTM Weekly Briefs from a page
    //     hierarchy to a `gtmWeeklyBriefs` database — Tool 6 should be rewritten
    //     to `pages.create({ parent: { database_id: NOTION_IDS.dbs.gtmWeeklyBriefs }})`
    //     and `REVENUE_PAGE_ID` removed entirely. Do not patch this ID — replace the logic.
    revenue:    "377fc8f4-554c-811e-af04-ef340c18ec34",
  },
};

const SQUAD_PAGE_IDS: Record<SquadId, string> = {
  atlas: NOTION_IDS.pages.squadAtlas,
  lumen: NOTION_IDS.pages.squadLumen,
  forge: NOTION_IDS.pages.squadForge,
};

export function getSquadPageId(squadId: SquadId): string {
  return SQUAD_PAGE_IDS[squadId];
}
