/**
 * teardown-workspace.ts
 *
 * Archives every Notion database and squad page created by bootstrap-workspace.ts,
 * then resets src/lib/notion-ids.ts to empty strings.
 *
 * Archives (moves to Notion trash) rather than hard-deleting so nothing is
 * unrecoverable. Safe to re-run after bootstrap creates the workspace again.
 *
 * Usage:  pnpm tsx scripts/teardown-workspace.ts
 *         pnpm tsx scripts/teardown-workspace.ts --dry-run
 */

import path from "path";
import fs from "fs";
import { getNotionClient } from "../src/lib/notion";
import { loadEnv } from "../src/lib/env";
import { NOTION_IDS } from "../src/lib/notion-ids";

const DRY_RUN = process.argv.includes("--dry-run");

async function archivePage(id: string, label: string): Promise<void> {
  if (!id) {
    console.log(`[skip]   ${label} — no ID recorded`);
    return;
  }
  if (DRY_RUN) {
    console.log(`[dry]    would archive ${label} (${id})`);
    return;
  }
  const client = getNotionClient();
  try {
    await client.pages.update({ page_id: id, archived: true });
    console.log(`[archive] ${label} (${id})`);
  } catch (err: unknown) {
    const msg = err instanceof Error ? err.message : String(err);
    console.warn(`[warn]   ${label} (${id}) — ${msg}`);
  }
}

function resetNotionIds(): void {
  const empty = `// AUTO-GENERATED by scripts/bootstrap-workspace.ts — do not edit manually.
// Run \`pnpm tsx scripts/bootstrap-workspace.ts\` to populate with real IDs.

export interface NotionIds {
  dbs: {
    mirrorGithub: string;
    mirrorJira: string;
    mirrorSlack: string;
    mirrorFigma: string;
    squads: string;
    prds: string;
    productRoadmap: string;
    squadWeeklySummary: string;
    masterEpdWeekly: string;
    agentRunLog: string;
  };
  pages: {
    squadAtlas: string;
    squadLumen: string;
    squadForge: string;
  };
}

export const NOTION_IDS: NotionIds = {
  dbs: {
    mirrorGithub: "",
    mirrorJira: "",
    mirrorSlack: "",
    mirrorFigma: "",
    squads: "",
    prds: "",
    productRoadmap: "",
    squadWeeklySummary: "",
    masterEpdWeekly: "",
    agentRunLog: "",
  },
  pages: {
    squadAtlas: "",
    squadLumen: "",
    squadForge: "",
  },
};
`;
  const outPath = path.resolve(__dirname, "../src/lib/notion-ids.ts");
  fs.writeFileSync(outPath, empty, "utf8");
  console.log(`\nReset ${outPath}`);
}

async function main(): Promise<void> {
  loadEnv(); // validate env is present even if we don't use all keys

  console.log("─".repeat(60));
  console.log(`Arcline Workspace Teardown${DRY_RUN ? " (DRY RUN)" : ""}`);
  console.log("─".repeat(60));

  const allEmpty = Object.values(NOTION_IDS.dbs).every((v) => v === "") &&
                   Object.values(NOTION_IDS.pages).every((v) => v === "");
  if (allEmpty) {
    console.log("notion-ids.ts has no IDs — nothing to archive.");
    process.exit(0);
  }

  // Archive databases (order matters: archive dependents before Squads)
  await archivePage(NOTION_IDS.dbs.agentRunLog,        "Agent Run Log");
  await archivePage(NOTION_IDS.dbs.masterEpdWeekly,    "Master EPD Weekly");
  await archivePage(NOTION_IDS.dbs.squadWeeklySummary, "Squad Weekly Summary");
  await archivePage(NOTION_IDS.dbs.productRoadmap,     "Product Roadmap");
  await archivePage(NOTION_IDS.dbs.prds,               "PRDs");
  await archivePage(NOTION_IDS.dbs.mirrorFigma,        "Mirror — Figma");
  await archivePage(NOTION_IDS.dbs.mirrorSlack,        "Mirror — Slack");
  await archivePage(NOTION_IDS.dbs.mirrorJira,         "Mirror — Jira");
  await archivePage(NOTION_IDS.dbs.mirrorGithub,       "Mirror — GitHub");
  await archivePage(NOTION_IDS.dbs.squads,             "Squads");

  // Archive squad pages
  await archivePage(NOTION_IDS.pages.squadAtlas, "Atlas page");
  await archivePage(NOTION_IDS.pages.squadLumen, "Lumen page");
  await archivePage(NOTION_IDS.pages.squadForge, "Forge page");

  if (!DRY_RUN) {
    resetNotionIds();
  }

  console.log("─".repeat(60));
  console.log(DRY_RUN ? "Dry run complete — no changes made." : "✓  Teardown complete.");
  console.log("─".repeat(60));
}

main().catch((err) => {
  console.error("\n[FATAL]", err instanceof Error ? err.message : err);
  process.exit(1);
});
